version: '3.7'

services:
    skoruba-sql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - "14333:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        volumes: 
            - "skoruba-identityserver-sql:/var/opt/mssql"
            
    sts:
        image: skoruba-identityserver-sts:latest
        ports: 
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development # <== otherwise will fail because of Skoruba.IdentityServer4.STS.Identity.Helpers.StartupHelpers:91
            - "ConnectionStrings:AdminConnection=Server=skoruba-sql, 1433;Database=IdentityServer4Admin; User Id=sa; Password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true"
        depends_on:
            - skoruba-sql
            
    admin:
        image: skoruba-identityserver-admin:latest
        ports: 
            - "5001:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development # <== otherwise will fail because of certificate error
            - "ConnectionStrings:AdminConnection=Server=skoruba-sql, 1433;Database=IdentityServer4Admin; User Id=sa; Password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true"
            - "AdminConfiguration:IdentityAdminBaseUrl=http://localhost:80"
            - "AdminConfiguration:IdentityAdminRedirectUri=http://localhost:80/signin-oidc"
            - "AdminConfiguration:IdentityServerBaseUrl=sts:80"
        depends_on:
            - skoruba-sql
            - sts
        
networks:
    default:
        external: 
            name: skoruba-identityserver-network
        
volumes:
    skoruba-identityserver-sql:
    